//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportPoint.Features.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportPoint.Features.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proximamente estará disponible..
        /// </summary>
        internal static string Alert_Message_BetaApp {
            get {
                return ResourceManager.GetString("Alert_Message_BetaApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpas, hubo un error tratando de acceder a los datos via internet..
        /// </summary>
        internal static string Alert_Message_InternetError {
            get {
                return ResourceManager.GetString("Alert_Message_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible ingresar a esta página con estos permisos..
        /// </summary>
        internal static string Alert_Message_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Message_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string Alert_OK {
            get {
                return ResourceManager.GetString("Alert_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK....
        /// </summary>
        internal static string Alert_OK_OKEllipsis {
            get {
                return ResourceManager.GetString("Alert_OK_OKEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feature no disponible..
        /// </summary>
        internal static string Alert_Title_FeatureNotAvailable {
            get {
                return ResourceManager.GetString("Alert_Title_FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron validar los permisos..
        /// </summary>
        internal static string Alert_Title_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Title_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado.
        /// </summary>
        internal static string Alert_Title_UnexpectedError {
            get {
                return ResourceManager.GetString("Alert_Title_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, inserte una URL Absoluta válida..
        /// </summary>
        internal static string Snack_Message_InvalidAbsoluteURL {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidAbsoluteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, inserte los datos de Usuario y Contraseña..
        /// </summary>
        internal static string Snack_Message_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer una conexión segura..
        /// </summary>
        internal static string Snack_Message_LogIn_NoTokenAvailable {
            get {
                return ResourceManager.GetString("Snack_Message_LogIn_NoTokenAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario o la contraseña ingresados son incorrectos..
        /// </summary>
        internal static string Snack_Message_Login_UserAndPasswordValuesNotMatches {
            get {
                return ResourceManager.GetString("Snack_Message_Login_UserAndPasswordValuesNotMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener el perfil del usuario..
        /// </summary>
        internal static string Snack_Message_Profile_NoProfileAvailable {
            get {
                return ResourceManager.GetString("Snack_Message_Profile_NoProfileAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo crear el usuario..
        /// </summary>
        internal static string Snack_Message_Profile_NoProfileCreated {
            get {
                return ResourceManager.GetString("Snack_Message_Profile_NoProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones guardadas..
        /// </summary>
        internal static string Snack_Message_SettingsSaved {
            get {
                return ResourceManager.GetString("Snack_Message_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, inserte todos los datos..
        /// </summary>
        internal static string Snack_Message_SignUp_EmptyValues {
            get {
                return ResourceManager.GetString("Snack_Message_SignUp_EmptyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        internal static string Snack_Message_SignUp_PasswordValuesNotMatches {
            get {
                return ResourceManager.GetString("Snack_Message_SignUp_PasswordValuesNotMatches", resourceCulture);
            }
        }
    }
}
